Repository GetDKAN/dkan-tools, pull requests merged in 2019-04, with the labels that each got.

#106 Commands to work with dkan2 and some tests.
  .gitignore
  assets/d8/composer.json
  assets/d8/site/default.services.yml
  assets/d8/site/settings.docker.php
  assets/docker/docker-compose.common.yml
  assets/docker/docker-compose.noproxy.yml
  assets/site/settings.docker.php
  composer.json
  composer.lock
  phpunit.xml
  src/Command/BasicCommands.php
  src/Command/TestCommands.php
  src/Drupal/V7/BasicCommands.php
  src/Drupal/V7/TestCommands.php
  src/Drupal/V8/BasicCommands.php
  src/Drupal/V8/DkanCommands.php
  src/Drupal/V8/DrupalCommands.php
  src/Drupal/V8/InitCommands.php
  tests/DktlV7Test.php
  tests/DktlV8Test.php
Labels: Code Review

#112 Fix typo in error messages
  src/Drupal/V7/MakeCommands.php
  src/Drupal/V8/BasicCommands.php
Labels: In Progress

#113 Fixing incorrect linking of modules and themes in D8.
  src/Drupal/V8/BasicCommands.php
Labels: In Progress

#111 Allow passing extra phpunit arguments somewhat directly via the robo …
  bin/dktl
  src/Drupal/V7/BasicCommands.php
  src/Drupal/V8/BasicCommands.php
  src/Drupal/V8/DkanCommands.php
Labels: PQDC

#116 Json form
  assets/d8/composer.json
  src/Drupal/V8/BasicCommands.php
Labels: In Progress

#117 Adding a command that runs phpunit tests in dkan and sends a coverage…
  src/Command/TestCommands.php
  src/Drupal/V8/DkanCommands.php
Labels: In Progress
